### ISSUE TITLE
Possible bug for time based restrictions

### ISSUE THREAD

**Issue by mull** [tandemdrive/ocpi-tariffs#64]
Hello 👋 

Comparing our own implementation to yours, I've found what I think is a misinterpretation of the (2.2.1) spec on your end. Consider the following tariff:

<details>
<summary>tariff.json</summary>

```
{
  "country_code": "FI",
  "party_id": "FOO",
  "id": "TDR1",
  "currency": "EUR",
  "elements": [{
    "price_components": [{
      "type": "ENERGY",
      "price": 0.25,
      "vat": 10.0,
      "step_size": 1
    }],
    "restrictions": {
      "day_of_week": ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY"],
      "start_time": "20:00",
      "end_time": "15:00"
    }
  }],
  "last_updated": "2018-12-17T17:15:01Z"
}

```

</details>

And these definitions regarding restrictions (11.4.6. TariffRestrictions class):
> start_time: Start time of day in local time, the time zone is defined in the time_zone field of the Location, for example 13:30, valid from this time of the day.

> end_time: End time of day in local time, the time zone is defined in the time_zone field of the Location, for example 19:45, valid until this time of the day. Same syntax as start_time. If end_time < start_time then the period wraps around to the next day. To stop at end of the day use: 00:00.

> day_of_week: Which day(s) of the week this TariffElement is active.

Is it not an error that the tool considers Monday 08:01 to be covered by the tariff?

It seems like the "logical and" instruction is ignored, as the start_time on Monday is clearly 20:00 (ending at Tuesday 15:00.)

> When more than one restriction is set, they are to be threaded as a logical AND. So all need to be valid before this tariff is active.

The "is it on a matching weekday"-check is indeed true, but the "is it within the start/end times" ought to to be false given the definitions of start_time and end_time above. What do you think?

Here is the CDR I used as input (which is confusing, since CDRs are the results of applying a tariff to some input 😬) for good measure:

<details>
<summary>cdr.json</summary>

```
{
  "country_code": "FI",
  "party_id": "FOO",
  "id": "12345",
  "cdr_token": {
    "uid": "012345678",
    "type": "RFID",
    "contract_id": "DE8ACC12E46L89"
  },
  "auth_method": "WHITELIST",
  "currency": "EUR",
  "start_date_time": "2023-12-04T07:00:00Z",
  "end_date_time": "2023-12-04T08:50:00Z",
  "charging_periods": [{
    "start_date_time": "2023-12-04T07:01:00Z",
    "dimensions": [{
      "type": "ENERGY",
      "volume": 10
    }]
  }],
  "total_cost": {
   "incl_vat": 0,
   "excl_vat": 0
  },
  "total_energy_cost": {
   "incl_vat": 1337,
   "excl_vat": 1337
  },
  "total_energy": 10,
  "total_time": 1,
  "last_updated": "2023-12-04T07:50:00Z"
}
```

</details>

**Comment by remkop22** [comment]
Hi @mull,

Thanks comparing the implementation and taking the time to bring this up!

> When more than one restriction is set, they are to be threaded as a logical AND. So all need to be valid before this tariff is active.

I interpret this line as to mean the following, evaluate each restriction separately and subsequently perform logical `AND` on all of them. So the following in python like psuedo code:

```python
def is_active(weekday, current_local_time):

    is_matching_weekday = weekday in set(["MON", "TUE", "WED", "THU", "FRI"])

    # Since `end_time` < `start_time` it wraps around midnight.
    is_matching_time = ("20:00" < current_local_time <= "23:59") or ("00:00" <= current_local_time < "15:00")

    return is_matching_weekday and is_matching_time
```

> Is it not an error that the tool considers Monday 08:01 to be covered by the tariff?
> It seems like the "logical and" instruction is ignored, as the start_time on Monday is clearly 20:00 (ending at Tuesday 15:00.)

I would say that the `start_time` is indeed `20:00` on a Monday and the end time `15:00` on a Tuesday, but just looking at the `time` and disregarding the weekday restriction for now, the `start_time` is also `20:00` on a Sunday, and the subsequent `end_time` is `15:00` on the Monday after.

So evaluating for the timestamp `2023-12-04T07:01:00Z` (disregarding timezone for sake of simplicity):

- Is the time between `20:00` and `15:00` (wrapping over midnight)? `07:01`, so **yes**
- Is the day of this timestamp in the set of all weekdays (excluding the weekend)? it's on a `Monday`, so **yes**

I guess if you'd want to exclude Monday morning you'd have to have a separate tariff element which matches just the Monday starting on `20:00`. 

This is my interpretation of the spec and I'm not 100% sure if it's correct, so please let me know if it differs from yours.

Thanks!

**Comment by mull** [comment]
Thanks for the response @remkop22 -- our interpretations differ indeed, but I see nothing in the spec that would favour one over the other. Which I suppose warrants an issue in the spec repo.

When you put it that way I think your interpretation is fair: there is no "connection" between day_of_week and start_time/end_time (and thus next day wrapping), so that 20:00-08:00 in isolation means "every day starting at 8pm until 8am the next day".

I think that's a fair interpretation, which my colleague is also a proponent for. So I think I'll have to change my implementation 🙃
